### GET string Hello World test
GET http://localhost:3000

### GET all contact records from local database
GET http://localhost:3000/contacts

### GET contact by ID (add any contactid from the collection of MongoDB)
GET http://localhost:3000/contacts/6a9f693009b49049f8d4ac43
